FROM postgres:10.1-alpine

MAINTAINER Carlos Rafael M Fernandes <carlos@hopetecno.com>

#-----------------------------------------------------------------------------------------------#
# Ajusta a configuração do PostgreSQL para ser possível fazer conexão remota ao banco de dados. #
#-----------------------------------------------------------------------------------------------#